### ISSUE TITLE
Not Posted related items are added automatically

### ISSUE THREAD

**Issue by eafarooqi** [tattersoftware/codeigniter4-relations#18]
Hi, 

looks like its related to the previous reported issue #17 , if related items are not posted in the form, they are added automatically in the related table.

```
$meeting= new Meeting($this->request->getPost());

if(!$meeting->roles){
     $meeting->roles = [];
}

$this->meetingModel->insert($meeting)
```

if roles are not posted, then have to set them as blank, otherwise few related items are added automatically to the table.

**Comment by MGatner** [comment]
Probably you're right that #17 fixes this. But what sort of model and database are you using that it inserts arrays?

**Comment by eafarooqi** [comment]
I mean multiple rows are inserted into database. using MySQL and CI default model

**Comment by MGatner** [comment]
Have you checked if this is still an issue?

**Comment by MGatner** [comment]
Closing as stale. Please reopen with more evidence if the issue persists.
