### ISSUE TITLE
Full Implementation Example

### ISSUE THREAD

**Issue by rlaurente** [tattersoftware/codeigniter4-relations#2]
Hi I just switch to codeigniter 4.

Can you please provide full example

Thanks

**Comment by MGatner** [comment]
I'm going to apply this module to a fork of https://github.com/codeigniter4projects/playground with live usage examples and some addition in-place docs. It will probably be a week or so though, so stay tuned. I'm glad to answer specific questions if you have any - the forum thread would be appropriate:

https://forum.codeigniter.com/thread-74447.html

**Comment by MGatner** [comment]
An example of using Relations within the CodeIgniter Playground can be found here: https://github.com/MGatner/playground/tree/relations

You can see exactly what I did in this commit, some Model loading and some Entity: https://github.com/MGatner/playground/commit/f6c395af7e975b125523b20c556d8844044a896e

This example can be browsed here: https://relations.igniter.be

**Comment by crustamet** [comment]
this example does not work anymore :o
