### ISSUE TITLE
Not working relations

### ISSUE THREAD

**Issue by ridoananda** [tattersoftware/codeigniter4-relations#26]
Sorry bro, why i always error when chain the method with()
Error: table t1 no related to table t2
I have use ModelTrait in my model but it same:(

**Comment by MGatner** [comment]
If the tables are indeed related then your schema is likely incorrect. Check out https://github.com/tattersoftware/codeigniter4-schemas for how to configure it. You might be interested in this thread on creating specific relations: https://github.com/tattersoftware/codeigniter4-schemas/issues/19

**Comment by MGatner** [comment]
Closing as stale. Please reopen with more evidence if the issue persists.
