### ISSUE TITLE
Relation same table twice or more

### ISSUE THREAD

**Issue by awasspl** [tattersoftware/codeigniter4-relations#29]
Hi guys,

Don't know if it's and issue or i make something wrong but with more than one relation with same table it's always return "last" FOREIGN KEY relation, ordering by key name.

Can You point me for a solution to get both relation listed in object?

example Invitation witch guest and inviting person both link with user table.

**Comment by MGatner** [comment]
You will probably need to create a schema for that manually, because (as you noted) it will only detect one relationship between the same two tables. Further discussion should happen in the `Schemas` repo since it is not really an issue with `Relations`.
