### ISSUE TITLE
For Windows File Name Special Character Error 

### ISSUE THREAD

**Issue by tugayilhan** [tattersoftware/codeigniter4-relations#3]
when i try to use on windows i got some error,
windows not allow special character for filename; example schemes:develop:table_name, then i changed ':' by '-' then fixed the problem.
`
\tatter\schemas\src\Archiver\Handlers\CacheHandler.php:

line 46
$this->cache->save($this->cacheKey . ':' . $table->name, $table, $this->config->ttl);
 to $this->cache->save($this->cacheKey . '-' . $table->name, $table, $this->config->ttl);	

tatter\schemas\src\Reader\Handlers\CacheHandler.php:	
line 74: 
$this->tables->$tableName = $this->cache->get($this->cacheKey . ':' . $tableName); 
to $this->tables->$tableName = $this->cache->get($this->cacheKey . '-' . $tableName); 

tatter\schemas\src\Traits\CacheHandlerTrait.php:

line   31: 		$this->cacheKey = 'schema:' . ENVIRONMENT;
 to	$this->cacheKey = 'schema-' . ENVIRONMENT;
`

**Comment by MGatner** [comment]
Wow I guess I've been off Windows a long time, I didn't realize colon was restricted! I will make the change to dashes. Feel free to send over a PR sooner.

**Comment by MGatner** [comment]
This was fixed in Schemas: https://github.com/tattersoftware/codeigniter4-schemas/commit/381708d0f7ee8b6ef2cb02ff0a9808aa812863ef
