### ISSUE TITLE
I created a new schema, but when I use "with" it returns "Table not present in schema:"

### ISSUE THREAD

**Issue by NathanAllmeida** [tattersoftware/codeigniter4-relations#44]
I created a new schema, but when I use "with" it returns "Table not present in schema:"
When i use in terminal
`php spark schemas -print`

I get the feedback that the "establishment" relationship exists
![image](https://user-images.githubusercontent.com/30378181/200005001-ad393d3a-4757-4089-a653-6c82166e6e8c.png)

But when I call the "with" I get the error:
`Table not present in schema: establishment`

**Comment by MGatner** [comment]
Can you share your entire schema? Maybe in Pastebin or GitHub Gist if it is very big.
